import React, { useEffect, useRef, useState } from 'react'
import { Marker, Polyline } from 'react-leaflet'
import L from 'leaflet'

// ── physics ───────────────────────────────────────────────────────────────────
const EARTH_RADIUS_M  = 6371000
const CORRECTION_MS   = 1500
const TURN_RATE_DEG_S = 3
const NM = 1852

const SPD_CRUISE   = 230
const SPD_APPROACH = 77
const SPD_FINAL    = 67
const SPD_FLARE    = 56
const GLIDE_SLOPE  = 0.05241   // tan(3°)

const DST_APPROACH = 92600   // 50 nm
const DST_FINAL    = 18520   // 10 nm
const DST_FLARE    =  5556   //  3 nm
const DST_TOUCHDOWN=   400

const FAF_NM  = 10    // final approach fix: 10 nm before threshold

// Path is generated by forward-simulating the plane's own turn physics, so the
// drawn line is always physically achievable. Lower turn rate = wider radius.
const SIM_TURN_RATE_DEG_S = 1.6   // gentle, wide turns (will loop if it can't line up)
const SIM_DT              = 1.0   // simulation step (seconds)

// ── geo helpers ───────────────────────────────────────────────────────────────
const toRad = d => d * Math.PI / 180

const calcBearing = (la1, lo1, la2, lo2) => {
  const φ1 = toRad(la1), φ2 = toRad(la2), Δλ = toRad(lo2 - lo1)
  const y = Math.sin(Δλ) * Math.cos(φ2)
  const x = Math.cos(φ1) * Math.sin(φ2) - Math.sin(φ1) * Math.cos(φ2) * Math.cos(Δλ)
  return ((Math.atan2(y, x) * 180 / Math.PI) + 360) % 360
}

const movePos = (lat, lon, hdg, distM) => {
  const φ1 = toRad(lat), λ1 = toRad(lon), θ = toRad(hdg), d = distM / EARTH_RADIUS_M
  const φ2 = Math.asin(Math.sin(φ1) * Math.cos(d) + Math.cos(φ1) * Math.sin(d) * Math.cos(θ))
  const λ2 = λ1 + Math.atan2(Math.sin(θ) * Math.sin(d) * Math.cos(φ1), Math.cos(d) - Math.sin(φ1) * Math.sin(φ2))
  return { lat: φ2 * 180 / Math.PI, lon: λ2 * 180 / Math.PI }
}

const distM = (la1, lo1, la2, lo2) =>
  Math.hypot((la2 - la1) * 111320, (lo2 - lo1) * 111320 * Math.cos(toRad(la1)))

const angDiff = (a, b) => Math.abs(((a - b + 540) % 360) - 180)

const lerpAngle = (from, to, t) => {
  const diff = ((to - from + 540) % 360) - 180
  return from + diff * t
}

const lerpSpeed = (cur, tgt, dt, rate = 8) => {
  const diff = tgt - cur
  const step = rate * dt
  return Math.abs(diff) < step ? tgt : cur + Math.sign(diff) * step
}

// ── runway picking (uses actual CSV coordinates for heading) ─────────────────
function pickRunway(runwaysMap, icao, planeLat, planeLon, airportLat, airportLon) {
  const rwys = runwaysMap?.[icao]
  if (!rwys?.length) return null

  const bearingToAirport = calcBearing(planeLat, planeLon, airportLat, airportLon)
  let best = null, bestDiff = 360

  for (const rwy of rwys) {
    if (!rwy.le_lat || !rwy.le_lon || !rwy.he_lat || !rwy.he_lon) continue

    // Heading from LE threshold toward HE = landing heading on LE end
    const leHdg = calcBearing(rwy.le_lat, rwy.le_lon, rwy.he_lat, rwy.he_lon)
    const leDiff = angDiff(leHdg, bearingToAirport)
    if (leDiff < bestDiff) {
      bestDiff = leDiff
      best = { id: rwy.le_ident, hdg: leHdg, tLat: rwy.le_lat, tLon: rwy.le_lon }
    }

    // Heading from HE threshold toward LE = landing heading on HE end
    const heHdg = calcBearing(rwy.he_lat, rwy.he_lon, rwy.le_lat, rwy.le_lon)
    const heDiff = angDiff(heHdg, bearingToAirport)
    if (heDiff < bestDiff) {
      bestDiff = heDiff
      best = { id: rwy.he_ident, hdg: heHdg, tLat: rwy.he_lat, tLon: rwy.he_lon }
    }
  }

  return best   // { id, hdg, tLat, tLon }  — hdg from actual coords, not ident
}

// Speed schedule by distance-to-threshold (used by both sim and runtime)
function speedForDist(toThr) {
  if (toThr > DST_APPROACH) return SPD_CRUISE
  if (toThr > DST_FINAL)    return SPD_APPROACH
  if (toThr > DST_FLARE)    return SPD_FINAL
  return SPD_FLARE
}

const LOOKAHEAD_M = 9000   // carrot distance ahead on the centerline (≈ turn radius)

// ── approach path: forward-simulate with carrot-chasing guidance ─────────────
// The plane follows ONE line — the runway centerline — by always aiming at a
// "carrot" a fixed distance ahead of its own projection onto that line. This
// pure-pursuit converges smoothly onto the centerline (no weaving) and then
// flies straight through to the threshold. Turn-rate-limited, so it makes a
// single wide turn (or a loop if pointed away) to capture the line.
function buildApproachWaypoints(planeLat, planeLon, planeHdg, runway) {
  const outbound  = (runway.hdg + 180) % 360
  const faf       = movePos(runway.tLat, runway.tLon, outbound, FAF_NM * NM)
  const threshold = { lat: runway.tLat, lon: runway.tLon }

  // Centerline direction = inbound course (toward threshold), as a unit N/E vector
  const courseRad = toRad(runway.hdg)
  const dirN = Math.cos(courseRad), dirE = Math.sin(courseRad)
  const cosT = Math.cos(toRad(threshold.lat))

  let lat = planeLat, lon = planeLon, hdg = planeHdg
  const pts = [{ lat, lon }]

  const maxSteps = 1500   // safety cap
  for (let i = 0; i < maxSteps; i++) {
    const toThr = distM(lat, lon, threshold.lat, threshold.lon)
    const speed = speedForDist(toThr)
    const step  = speed * SIM_DT

    if (toThr < step * 1.2) { pts.push({ ...threshold }); break }

    // Project plane onto the centerline. alongTrack: 0 = threshold,
    // negative = approach side (behind threshold).
    const dN = (lat - threshold.lat) * 111320
    const dE = (lon - threshold.lon) * 111320 * cosT
    const alongTrack = dN * dirN + dE * dirE

    // Carrot = a point LOOKAHEAD ahead along the line, never past the threshold
    const carrotAlong = Math.min(alongTrack + LOOKAHEAD_M, 0)
    const carrotLat = threshold.lat + (carrotAlong * dirN) / 111320
    const carrotLon = threshold.lon + (carrotAlong * dirE) / (111320 * cosT)

    const desiredHdg = calcBearing(lat, lon, carrotLat, carrotLon)
    const diff       = ((desiredHdg - hdg + 540) % 360) - 180
    const maxTurn    = SIM_TURN_RATE_DEG_S * SIM_DT
    hdg = (hdg + Math.sign(diff) * Math.min(Math.abs(diff), maxTurn) + 360) % 360

    const moved = movePos(lat, lon, hdg, step)
    lat = moved.lat; lon = moved.lon
    pts.push({ lat, lon })
  }

  const curveLine      = pts.map(p => [p.lat, p.lon])
  const centerlineLine = [[faf.lat, faf.lon], [runway.tLat, runway.tLon]]

  return { allWPs: pts, curveLine, centerlineLine, extraLine: [], faf }
}

// ── icon ──────────────────────────────────────────────────────────────────────
const makePlaneIcon = (isSelected, landing) => {
  const color = landing ? '#22c55e' : isSelected ? '#fff' : '#666'
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" style="transform:rotate(0deg);">
    <path fill="${color}" d="M12,2A1.5,1.5,0,0,0,10.5,3.5V8.5L2,14v2l8.5-2.5V19L8,21v1l4-1,4,1V21l-2.5-2V13.5L22,16V14L13.5,8.5V3.5A1.5,1.5,0,0,0,12,2Z"/>
  </svg>`
  return L.divIcon({ html: svg, className: '', iconSize: [28, 28], iconAnchor: [14, 14] })
}

// ── ADS-B extrapolation ───────────────────────────────────────────────────────
const extrapolate = (state, now) => {
  const elapsed = Math.max(0, (now - state.updatedAt) / 1000)
  if (!state.velocity || !state.heading || elapsed === 0) return { lat: state.lat, lon: state.lon }
  return movePos(state.lat, state.lon, state.heading, state.velocity * elapsed)
}
const getDisplayPos = (state, now) => {
  if (!state.correcting) return extrapolate(state, now)
  const t = Math.min(1, (now - state.corrStart) / CORRECTION_MS)
  const pos = {
    lat: state.corrFrom.lat + (state.corrTo.lat - state.corrFrom.lat) * (1 - (1 - t) ** 2),
    lon: state.corrFrom.lon + (state.corrTo.lon - state.corrFrom.lon) * (1 - (1 - t) ** 2),
  }
  if (t >= 1) { state.correcting = false; state.lat = state.corrTo.lat; state.lon = state.corrTo.lon; state.updatedAt = now }
  return pos
}

// ── component ─────────────────────────────────────────────────────────────────
export default function AnimatedAircraftMarker({
  craft, isSelected, landingTarget, runwaysMap, livePosRef, onSelect, onLandingComplete,
}) {
  const markerRef        = useRef(null)
  const onSelectRef      = useRef(onSelect)
  const craftRef         = useRef(craft)
  const landingRef       = useRef(landingTarget)
  const runwaysRef       = useRef(runwaysMap)
  const livePosRefRef    = useRef(livePosRef)
  const onLandingRef     = useRef(onLandingComplete)

  useEffect(() => { onSelectRef.current   = onSelect         }, [onSelect])
  useEffect(() => { craftRef.current      = craft            }, [craft])
  useEffect(() => { landingRef.current    = landingTarget    }, [landingTarget])
  useEffect(() => { runwaysRef.current    = runwaysMap       }, [runwaysMap])
  useEffect(() => { livePosRefRef.current = livePosRef       }, [livePosRef])
  useEffect(() => { onLandingRef.current  = onLandingComplete }, [onLandingComplete])

  const handleClick = useRef(() => onSelectRef.current?.(craftRef.current)).current

  // Visual path state (drives Polyline renders)
  const [pathVis, setPathVis] = useState(null)
  // { curveLine: [[lat,lon],...], centerlineLine: [[lat,lon],[lat,lon]] }

  const stateRef = useRef({
    lat: craft.lat, lon: craft.lon,
    heading: craft.heading, velocity: craft.velocity,
    updatedAt: Date.now(),
    correcting: false,
    corrFrom: { lat: craft.lat, lon: craft.lon },
    corrTo:   { lat: craft.lat, lon: craft.lon },
    corrStart: 0,
    displayHeading:   craft.heading ?? 0,
    commandedHeading: craft.heading ?? 0,
    lastTick: Date.now(),
    // Landing
    landing:     false,
    runway:      null,
    waypoints:   [],    // [{lat,lon}] full path the plane follows
    wpIdx:       0,     // current waypoint index
    landSpeed:   craft.velocity ?? SPD_CRUISE,
    landAlt:     craft.baroAlt  ?? 10000,
    landPhase:   'cruise',   // cruise|approach|final|flare|roll|done
    cLat:        craft.lat,  // current commanded lat
    cLon:        craft.lon,
  })

  // Update ADS-B corrections
  useEffect(() => {
    const state = stateRef.current, now = Date.now()
    const cur = getDisplayPos(state, now)
    const d   = distM(cur.lat, cur.lon, craft.lat, craft.lon)
    if (d > 15) {
      state.correcting = true; state.corrFrom = cur
      state.corrTo = { lat: craft.lat, lon: craft.lon }; state.corrStart = now
    } else {
      state.correcting = false; state.lat = craft.lat; state.lon = craft.lon; state.updatedAt = now
    }
    state.heading  = craft.heading
    state.velocity = craft.velocity
    if (!state.landing && craft.baroAlt != null) state.landAlt = craft.baroAlt
  }, [craft.lat, craft.lon, craft.heading, craft.velocity])

  // Enter / exit landing mode
  useEffect(() => {
    const state = stateRef.current
    if (!landingTarget) {
      state.landing = false; state.runway = null; state.waypoints = []; state.wpIdx = 0
      setPathVis(null)
      return
    }

    const now = Date.now()
    const cur = getDisplayPos(state, now)

    const runway = pickRunway(runwaysMap, landingTarget.airport, cur.lat, cur.lon, landingTarget.lat, landingTarget.lon)
    if (!runway) return   // no runway data yet — wait for runwaysMap to load

    const { allWPs, curveLine, centerlineLine, extraLine } = buildApproachWaypoints(cur.lat, cur.lon, state.displayHeading, runway)

    state.landing          = true
    state.runway           = runway
    state.waypoints        = allWPs
    state.wpIdx            = 0
    state.commandedHeading = state.displayHeading
    state.cLat             = cur.lat
    state.cLon             = cur.lon
    state.landSpeed        = Math.max(state.velocity ?? SPD_CRUISE, SPD_APPROACH)
    state.landAlt          = craftRef.current?.baroAlt ?? 10000
    state.landPhase        = 'cruise'

    setPathVis({ curveLine, centerlineLine, extraLine })
  }, [landingTarget, runwaysMap])   // re-run if runwaysMap loads after landingTarget is set

  useEffect(() => {
    const marker = markerRef.current
    if (marker) marker.setIcon(makePlaneIcon(isSelected, !!landingTarget))
  }, [isSelected, landingTarget])

  // rAF loop
  useEffect(() => {
    let frameId

    const tick = () => {
      const marker = markerRef.current
      if (!marker) { frameId = requestAnimationFrame(tick); return }

      const state = stateRef.current
      const now   = Date.now()
      const dt    = Math.min(0.1, (now - state.lastTick) / 1000)
      state.lastTick = now

      let pos

      if (state.landing && state.waypoints.length > 0) {
        const runway = state.runway
        const threshold = runway ? { lat: runway.tLat, lon: runway.tLon } : null
        const toThreshold = threshold ? distM(state.cLat, state.cLon, threshold.lat, threshold.lon) : 0

        // ── phase transitions ──────────────────────────────────────────
        if (state.landPhase === 'cruise'   && toThreshold < DST_APPROACH) state.landPhase = 'approach'
        if (state.landPhase === 'approach' && toThreshold < DST_FINAL)    state.landPhase = 'final'
        if (state.landPhase === 'final'    && toThreshold < DST_FLARE)    state.landPhase = 'flare'
        if (state.landPhase === 'flare'    && toThreshold < DST_TOUCHDOWN) {
          state.landPhase = 'roll'; state.landAlt = 0
        }

        if (state.landPhase === 'done') {
          pos = { lat: state.cLat, lon: state.cLon }
        } else if (state.landPhase === 'roll') {
          state.landSpeed = lerpSpeed(state.landSpeed, 0, dt, 4)
          if (state.landSpeed < 0.5) {
            state.landSpeed = 0; state.landPhase = 'done'
            if (onLandingRef.current) { onLandingRef.current(); onLandingRef.current = null }
          }
          const moved = movePos(state.cLat, state.cLon, state.commandedHeading, state.landSpeed * dt)
          state.cLat = moved.lat; state.cLon = moved.lon; state.landAlt = 0
          pos = { lat: state.cLat, lon: state.cLon }
        } else {
          // ── target speed ───────────────────────────────────────────────
          const targetSpeed =
            state.landPhase === 'cruise'   ? SPD_CRUISE :
            state.landPhase === 'approach' ? SPD_APPROACH :
            state.landPhase === 'final'    ? SPD_FINAL : SPD_FLARE
          state.landSpeed = lerpSpeed(state.landSpeed, targetSpeed, dt, 5)

          // ── arc-length path following — trace the polyline exactly ──────
          // Walk forward along the waypoint chain by (speed * dt) metres, so
          // the plane sits exactly on the drawn line and never cuts corners.
          let budget = state.landSpeed * dt
          while (budget > 0 && state.wpIdx < state.waypoints.length) {
            const tgt     = state.waypoints[state.wpIdx]
            const segDist = distM(state.cLat, state.cLon, tgt.lat, tgt.lon)
            const segBrg  = calcBearing(state.cLat, state.cLon, tgt.lat, tgt.lon)
            state.commandedHeading = segBrg
            if (segDist <= budget) {
              // reach this waypoint, continue with leftover budget
              state.cLat = tgt.lat; state.cLon = tgt.lon
              budget -= segDist
              state.wpIdx++
            } else {
              // partial step along the current segment
              const moved = movePos(state.cLat, state.cLon, segBrg, budget)
              state.cLat = moved.lat; state.cLon = moved.lon
              budget = 0
            }
          }
          pos = { lat: state.cLat, lon: state.cLon }

          // ── altitude: glide slope from threshold ───────────────────────
          const toThr = distM(state.cLat, state.cLon, threshold.lat, threshold.lon)
          const glideAlt = Math.max(0, toThr * GLIDE_SLOPE)
          if (state.landPhase !== 'cruise') {
            state.landAlt = lerpSpeed(state.landAlt, glideAlt, dt, 12)
          }
        }

      } else {
        pos = getDisplayPos(state, now)
        if (state.heading != null) state.commandedHeading = state.heading
      }

      state.displayHeading = lerpAngle(state.displayHeading, state.commandedHeading, 0.12)
      marker.setLatLng([pos.lat, pos.lon])

      if (livePosRefRef.current) {
        livePosRefRef.current.current = {
          lat:      pos.lat,
          lon:      pos.lon,
          velocity: state.landing ? state.landSpeed : state.velocity,
          alt:      state.landing ? state.landAlt   : craftRef.current?.baroAlt,
          phase:    state.landing ? state.landPhase : null,
        }
      }

      const el = marker.getElement()
      if (el) { const svg = el.querySelector('svg'); if (svg) svg.style.transform = `rotate(${state.displayHeading}deg)` }

      frameId = requestAnimationFrame(tick)
    }

    frameId = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(frameId)
  }, [])

  return (
    <>
      <Marker
        ref={markerRef}
        position={[craft.lat, craft.lon]}
        icon={makePlaneIcon(isSelected, !!landingTarget)}
        zIndexOffset={isSelected ? 1000 : 0}
        eventHandlers={{ click: handleClick }}
      />

      {/* extension arc when plane is too close / angle too sharp — dashed */}
      {pathVis?.extraLine?.length > 1 && (
        <Polyline
          positions={pathVis.extraLine}
          pathOptions={{ color: '#22c55e', weight: 1.5, dashArray: '4 8', opacity: 0.45 }}
          interactive={false}
        />
      )}

      {/* intercept curve — dashed green */}
      {pathVis?.curveLine?.length > 1 && (
        <Polyline
          positions={pathVis.curveLine}
          pathOptions={{ color: '#22c55e', weight: 1.5, dashArray: '8 6', opacity: 0.65 }}
          interactive={false}
        />
      )}

      {/* ILS centerline FAF → threshold — solid green */}
      {pathVis?.centerlineLine && (
        <Polyline
          positions={pathVis.centerlineLine}
          pathOptions={{ color: '#22c55e', weight: 2.5, opacity: 0.9 }}
          interactive={false}
        />
      )}
    </>
  )
}
